using Basje.AdventOfCode.Y2024.D08;

namespace Basje.AdventOfCode.Y2024.Tests;

public static class Day08Tests
{
    [Fact]
    public static void Part1()
    {
        var solution = new Day08();
        const string input = """
                             ............
                             ........0...
                             .....0......
                             .......0....
                             ....0.......
                             ......A.....
                             ............
                             ............
                             ........A...
                             .........A..
                             ............
                             ............
                             """;

        var answer = solution.SolvePart1(input);

        answer.Should().Be(14);
    }

    [Fact]
    public static void Part2()
    {
        var solution = new Day08();
        const string input = """
                             ............
                             ........0...
                             .....0......
                             .......0....
                             ....0.......
                             ......A.....
                             ............
                             ............
                             ........A...
                             .........A..
                             ............
                             ............
                             """;
        
        var answer = solution.SolvePart2(input);
        
        answer.Should().Be(34);
    }
}